### ISSUE TITLE
Expose event to handle server-issued disconnects

### ISSUE THREAD

**Issue by mat1jaczyyy** [Proximitynow19/TETR.JS#58]
A client can be disconnected by the server due to various reasons, including regular TETR.IO maintenance, which poses a problem for long-running bots.

Expose an event to notify bots when they've been disconnected and why, allowing them to handle reconnecting and re-setting up any bot state / in-game actions (such as opening rooms) themselves upon successful reconnection.

**Comment by mat1jaczyyy** [comment]
Note: a hotfix was already applied to seemingly random `ws` closes here:
https://github.com/tetrjs/tetr.js/blob/4ceff0b119c440c26997f3807cd44f4fe26cd1b2/src/ws/WebSocketManager.ts#L166-L168

I'm not sure if these are just random disconnects due to long idle periods, or the `ws` just closes silently upon maintenance.

**Comment by Sup3rFire** [comment]
Fixed

**Comment by mat1jaczyyy** [comment]
if there is no apparent reason for a disconnect (nothing happened on the ribbon, ws just closed itself), can this also be raised as an event rather than just silently reconnecting?
