### ISSUE TITLE
Expose singleplayer record information about player

### ISSUE THREAD

**Issue by mat1jaczyyy** [Proximitynow19/TETR.JS#59]
Player data currently doesn't contain 40L/Blitz record information because it's in a separate Tetra Channel API endpoint.

We're currently hacking this together in [EU Cannon](https://github.com/EUCannon/bot/blob/ca97461f369bbce65f4aeedf02243434ae3637a8/index.js#L86-L87).

**Comment by Sup3rFire** [comment]
fixed
